export enum OverlayEnum {
  successToast = 'successToast',
  loadingToast = 'loadingToast',
  topTips = 'topTips',
  dialog = 'dialog',
  textInputDialog = 'textInputDialog',
  actionSheet = 'actionSheet',
  notebookPicker = 'notebookPicker',
  identityPicker = 'identityPicker',
  imagePreview = 'imagePreview',
  videoPreview = 'videoPreview',
  videoPlayer = 'videoPlayer',
  longPressMenu = 'longPressMenu',
  voiceRecording = 'voiceRecording',
}
